# Тесты для ADD

In [ ]:
import random

import numpy as np
import osmnx as ox
import pandas as pd
import geopandas as gpd

import genesis as genesis


# Версии библиотек
print('OSMnx:', ox.__version__,
      '\nGeoPandas:', gpd.__version__,
      '\nPandas:', pd.__version__,
      '\ngenesis:', genesis.__version__,
      )

OSMnx: 2.0.1
GeoPandas: 1.0.1
Pandas: 2.1.1
genesis: 0.2.001

In [ ]:
# 1. Загрузка исходных данных
## Загрузка ГДС
G = ox.load_graphml(r'tests\data\test_rng.ml')

## Упрощение графа (уменьшение количества узлов)
G = ox.simplification.simplify_graph(G)

## Загрузка зданий
buildings = gpd.read_file(r'tests\data\buildings.gpkg')
### Сопоставление зданий с ближайшими узлами ГДС
centroids = ox.projection.project_gdf(buildings).geometry.centroid
buildings['node'] = ox.distance.nearest_nodes(ox.project_graph(G), 
                                              centroids.x,
                                              centroids.y
                                              )
# Дополняем набор весами
weights = [random.randint(1, 10) for _ in range(len(buildings))]
buildings['weight'] = weights

In [44]:
from genesis.states import get_atm

## Расчет матрицы прибытия
matrix = get_atm(G,
                 data             = buildings,
                 data_sample_size = 20,
                 cutoff           = 10,
                 )

|########################################| 100.0%

In [45]:
matrix

,290700365,290700367,290700398,290700400,290700427,290700436,290700478,360828220,426923792,426923793,...,10861549504,10861562805,10861562811,10861562814,10861562815,10861562816,10861562817,10861562818,10861562819,10861562821
558,NaN,NaN,7.043686,6.804371,5.038276,3.865851,2.363445,NaN,NaN,6.589321,...,7.630059,7.820196,6.516707,6.839943,6.868869,6.577687,6.605138,6.652866,6.863681,7.401563
190,NaN,NaN,7.457113,7.217798,5.317703,NaN,9.159117,6.089718,3.383394,3.769276,...,8.081801,8.258514,9.195153,8.902042,8.930968,9.369845,9.136847,9.089119,8.925780,9.352473
1196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.779983,8.685550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,NaN,NaN,7.387702,7.148388,5.382293,4.209867,4.647409,NaN,NaN,6.933337,...,5.710247,5.900384,4.596895,4.920131,4.949057,4.657875,4.685326,4.733054,4.943869,5.481751
1504,NaN,NaN,NaN,9.950885,8.050790,NaN,NaN,9.599865,6.893541,5.799108,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1308,NaN,NaN,9.126445,8.887131,7.121036,5.948610,5.903551,NaN,NaN,8.672080,...,7.197115,7.387252,6.335638,6.376874,6.405800,6.114618,6.142068,6.189797,6.400612,7.175016
30,NaN,NaN,7.417161,7.177847,5.277751,NaN,9.119165,6.693067,3.986743,4.585496,...,8.041849,8.218562,9.155201,8.862090,8.891016,9.329893,9.096895,9.049167,8.885828,9.312521
810,NaN,NaN,8.333374,8.094060,6.327965,5.155539,4.631968,NaN,NaN,7.879009,...,6.655919,6.846056,5.542567,5.865803,5.894729,5.603547,5.630998,5.678726,5.889541,6.427423
174,NaN,NaN,5.946206,5.706892,3.806796,NaN,7.648211,8.166187,5.459863,1.834340,...,6.570894,6.747607,7.684246,7.391135,7.420061,7.858938,7.625940,7.578212,7.414873,7.841566
1463,7.066927,6.704975,4.191314,6.874914,NaN,9.023802,NaN,NaN,9.550965,NaN,...,5.902442,5.831784,6.884569,6.481703,6.510629,6.516508,6.283510,6.294626,6.505441,7.173113
343,4.606692,4.244739,NaN,NaN,NaN,NaN,NaN,9.797054,7.090730,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
986,4.821569,5.183522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
308,NaN,NaN,5.155318,4.916004,3.015908,9.451104,6.857323,8.846281,6.139957,1.742983,...,5.780006,5.956719,6.893358,6.600247,6.629173,7.068050,6.835052,6.787324,6.623985,7.050678
949,4.821569,5.183522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,NaN,NaN,8.270959,8.031645,6.131550,NaN,9.972964,6.200310,3.493986,3.879868,...,8.895648,9.072361,NaN,9.715888,9.744814,NaN,9.950694,9.902965,9.739626,NaN
1238,NaN,NaN,NaN,NaN,9.643812,NaN,NaN,NaN,8.486563,7.392130,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,NaN,NaN,9.278040,9.038726,7.272631,6.100205,2.619046,NaN,NaN,8.823675,...,8.370330,8.560467,7.256978,7.580214,7.609140,7.317958,7.345409,7.393137,7.603952,8.141834
1379,NaN,NaN,5.077313,4.837999,3.071904,1.899478,5.553910,NaN,8.884870,4.622948,...,4.517988,4.708125,3.404636,3.727872,3.756798,3.465616,3.493067,3.540795,3.751610,4.289492
1014,3.397111,3.035158,NaN,NaN,NaN,NaN,NaN,9.609113,6.902789,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1211,NaN,NaN,NaN,NaN,9.362634,NaN,NaN,NaN,8.205385,7.110952,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
matrix = matrix <= 10
matrix

,290700365,290700367,290700398,290700400,290700427,290700436,290700478,360828220,426923792,426923793,...,10861549504,10861562805,10861562811,10861562814,10861562815,10861562816,10861562817,10861562818,10861562819,10861562821
558,False,False,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
190,False,False,True,True,True,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1196,False,False,False,False,False,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
496,False,False,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
1504,False,False,False,True,True,False,False,True,True,True,...,False,False,False,False,False,False,False,False,False,False
1308,False,False,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
30,False,False,True,True,True,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
810,False,False,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
174,False,False,True,True,True,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1463,True,True,True,True,False,True,False,False,True,False,...,True,True,True,True,True,True,True,True,True,True
343,True,True,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
986,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
308,False,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
949,True,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59,False,False,True,True,True,False,True,True,True,True,...,True,True,False,True,True,False,True,True,True,False
1238,False,False,False,False,True,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False
719,False,False,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
1379,False,False,True,True,True,True,True,False,True,True,...,True,True,True,True,True,True,True,True,True,True
1014,True,True,False,False,False,False,False,True,True,False,...,False,False,False,False,False,False,False,False,False,False
1211,False,False,False,False,True,False,False,False,True,True,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Пример DataFrame
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6]
})

# Пример Series
s = pd.Series([10, 20, 30], index=df.index)

# Умножение всех столбцов на Series
result_df = df.mul(s, axis=0)
print(result_df)

    A    B
0  10   40
1  40  100
2  90  180

In [ ]:
weights = buildings['weight'].loc[matrix.index]
matrix = matrix.mul(weights, axis=0)
matrix

,290700365,290700367,290700398,290700400,290700427,290700436,290700478,360828220,426923792,426923793,...,10861549504,10861562805,10861562811,10861562814,10861562815,10861562816,10861562817,10861562818,10861562819,10861562821
558,0,0,3,3,3,3,3,0,0,3,...,3,3,3,3,3,3,3,3,3,3
190,0,0,3,3,3,0,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
1196,0,0,0,0,0,0,0,0,2,2,...,0,0,0,0,0,0,0,0,0,0
496,0,0,2,2,2,2,2,0,0,2,...,2,2,2,2,2,2,2,2,2,2
1504,0,0,0,7,7,0,0,7,7,7,...,0,0,0,0,0,0,0,0,0,0
1308,0,0,5,5,5,5,5,0,0,5,...,5,5,5,5,5,5,5,5,5,5
30,0,0,3,3,3,0,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
810,0,0,9,9,9,9,9,0,0,9,...,9,9,9,9,9,9,9,9,9,9
174,0,0,9,9,9,0,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
1463,8,8,8,8,0,8,0,0,8,0,...,8,8,8,8,8,8,8,8,8,8
343,3,3,0,0,0,0,0,3,3,0,...,0,0,0,0,0,0,0,0,0,0
986,5,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
308,0,0,6,6,6,6,6,6,6,6,...,6,6,6,6,6,6,6,6,6,6
949,6,6,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
59,0,0,5,5,5,0,5,5,5,5,...,5,5,0,5,5,0,5,5,5,0
1238,0,0,0,0,2,0,0,0,2,2,...,0,0,0,0,0,0,0,0,0,0
719,0,0,3,3,3,3,3,0,0,3,...,3,3,3,3,3,3,3,3,3,3
1379,0,0,1,1,1,1,1,0,1,1,...,1,1,1,1,1,1,1,1,1,1
1014,5,5,0,0,0,0,0,5,5,0,...,0,0,0,0,0,0,0,0,0,0
1211,0,0,0,0,10,0,0,0,10,10,...,0,0,0,0,0,0,0,0,0,0

In [65]:
node_id = matrix.columns[np.argmax(np.sum(matrix, axis=0))]
node_id

426923872

In [66]:
matrix[node_id]

558      3
190      3
1196     2
496      2
1504     7
1308     5
30       3
810      9
174      9
1463     0
343      3
986      0
308      6
949      0
59       5
1238     2
719      3
1379     1
1014     5
1211    10
Name: 426923872, dtype: int64